site_name: HUGO
theme:
  name: "readthedocs"
  highlightjs: true
  hljs_languages:
    - yaml
    - toml
docs_dir: src
site_dir: docs
nav:
  - Home: index.md
  - 事前準備:
    - 00_prepare/00_hugo.md
    - 00_prepare/01_vscode.md
    - 00_prepare/02_git.md
  - サイトと記事作成:
    - 01_quickstart/00_add-site.md
    - 01_quickstart/01_add-article.md
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - fontawesome_markdown
  - footnotes
  - codehilite:
      linenums: true
extra_css:
  - "https://fonts.googleapis.com/earlyaccess/notosansjapanese.css"
  - "https://fonts.googleapis.com/css?family=Open+Sans:600,800"
  - "css/custom.css"
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
