site_name: HUGO
theme:
  name: "readthedocs"
  highlightjs: true
  hljs_languages:
    - yaml
    - toml
docs_dir: src
site_dir: docs
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - fontawesome_markdown
  - footnotes
extra_css:
  - "https://fonts.googleapis.com/earlyaccess/notosansjapanese.css"
  - "https://fonts.googleapis.com/css?family=Open+Sans:600,800"
  - "css/custom.css"
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
